# Generated by Django 2.0.2 on 2018-06-19 19:29

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebhookTitle', models.CharField(max_length=400)),
                ('NotificationTemplateText', tinymce.models.HTMLField()),
                ('RootURL', models.URLField()),
                ('WebhookURL', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Submit, Review, Collaborate, Deliver ', max_length=255, verbose_name='status')),
                ('ticketId', models.IntegerField(default=-1, help_text=' ', verbose_name='ticketId')),
                ('title', models.CharField(help_text=' ', max_length=255, verbose_name='title')),
                ('ownerName', models.CharField(help_text=' ', max_length=255, verbose_name='ownerName')),
                ('ownerEmail', models.CharField(help_text=' ', max_length=255, verbose_name='ownerEmail')),
                ('createdDate', models.CharField(help_text=' ', max_length=255, verbose_name='createdDate')),
                ('description', models.CharField(help_text=' ', max_length=255, verbose_name='description')),
                ('expectedTime', models.CharField(help_text=' ', max_length=255, verbose_name='expectedTime')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebhookName', models.URLField()),
                ('DataOut', tinymce.models.HTMLField()),
                ('WebhookStatus', models.CharField(max_length=400)),
            ],
        ),
    ]
