# Generated by Django 2.0.2 on 2018-06-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Submit, Review, Collaborate, Deliver ', max_length=255, verbose_name='status')),
                ('ticketId', models.IntegerField(default=-1, help_text=' ', verbose_name='ticketId')),
                ('title', models.CharField(help_text=' ', max_length=255, verbose_name='title')),
                ('ownerName', models.CharField(help_text=' ', max_length=255, verbose_name='ownerName')),
                ('ownerEmail', models.CharField(help_text=' ', max_length=255, verbose_name='ownerEmail')),
                ('createdDate', models.CharField(help_text=' ', max_length=255, verbose_name='createdDate')),
                ('description', models.CharField(help_text=' ', max_length=255, verbose_name='description')),
                ('expectedTime', models.CharField(help_text=' ', max_length=255, verbose_name='expectedTime')),
            ],
        ),
    ]
