# Generated by Django 2.0.2 on 2018-06-15 16:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebhookName', models.URLField(unique=True)),
                ('WebhookID', models.IntegerField(unique=True)),
                ('WebhookStatus', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='NotificationTemplate_text',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='Webhook_id',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='NotificationTemplateText',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='WebhookID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='WebhookURL',
            field=models.URLField(unique=True),
        ),
    ]
