# Generated by Django 2.0.2 on 2018-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_auto_20180615_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='id',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='WebhookTitle',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='WebhookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestvalue',
            name='expectedTime',
            field=models.CharField(help_text=' ', max_length=255, verbose_name='expectśdTime'),
        ),
    ]
