# Generated by Django 2.0.2 on 2018-06-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_webhook_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webhook_detail',
            new_name='Initiative',
        ),
    ]
