# Generated by Django 2.0.6 on 2018-06-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_auto_20180611_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StringTemplate',
            new_name='NotificationTemplate',
        ),
        migrations.RenameModel(
            old_name='Initiative',
            new_name='RequestValue',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='StringTemplate_text',
            new_name='NotificationTemplate_text',
        ),
    ]
